### ISSUE TITLE
Add DB initialization to CLI

### ISSUE THREAD

**Issue by ponchofiesta** [tuub/kitodo-mediaserver#103]
For an easier setup the creation of database tables should be possible via a CLI command. To make this work for every supported DB platform the SQL generation should be handled by Hibernate. If it is possible, the schema.sql should be removed.

**Comment by ponchofiesta** [comment]
This CLI command (`InitDbCommand`) will create the database schema for the configured database automatically. It will also run data.sql with initial data. The schema.sql isn't needed anymore.

To get needed settings by Hibernate the `HibernateIntegrator` hooks into the startup process and saves the metadata into `HibernateInfo`. The metadata is used by Hibernates SchemaExport.

**Comment by johlton** [comment]
When running the CLI with initDB (from current master) I get the following error: 

> org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of class path resource [initial-data.sql]: INSERT INTO user (username, password, name, enabled) VALUES ('admin', '$2a$10$oxfH7pRjIZcyB97LJ7/eSeSBEQyUE65kBiOZYADJ4wFYPkD2YqMiG', 'Administrator', 1); nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mediaserver.user' doesn't exist 

It actually creates the action_data table, but crashes then. MySQL logs the CREATE TABLE queries but no table shows up.

**Comment by johlton** [comment]
I assumed building core and cli would be enough which was not the case. Works like a charm.
