### ISSUE TITLE
Do we still need the ImporterApplication

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#111]
Since the importer now is executed in the CLI, there should be no need for the ImporterApplication class, or am I missing something?

**Comment by ponchofiesta** [comment]
I assume it isn't needed anymore and can be removed. Also log messages are written to cli.log, so the applicantion.yml could be removed too if there is nothing else in it.

**Comment by pbroman** [comment]
OK. Removed the spring-boot-maven-plugin as well, no longer needed.
