### ISSUE TITLE
Hibernate init creates MyISAM, join table missing

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#125]
If you create the database in MySQL using the cli with initDb you get MyISAM tables. Since these cannot handle foreign keys, there are no foreign key defined in the database, which of course may lead to inconsistencies.
Moreover, the join table between work and collection (see #121) is not created by initdb.

**Comment by ponchofiesta** [comment]
Yes, I assume, this is for backward compatibility. We can set the Hibernate dialect to MySQL57Dialect (or something like that) in local.yml to use InnoDB storage engine by default. But this depends on the database system used.

**Comment by pbroman** [comment]
Aaah, yes, now it's working. 
I think we should put it in default.yml, since we already have mysql as default datasource.
I make a pull request.

**Comment by pbroman** [comment]
But, just as a reminder, you're supposed to be on vacation. ;)

**Comment by ponchofiesta** [comment]
Thank you for using the automated solution system by @ponchofiesta. Have a nice day. 😄
