### ISSUE TITLE
Make collection and hostId searchable in the UI

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#129]
We have extended the database and the WorkDataReader with collection and hostId (for multi-volumed works). Purpose: make it possible to find all works belonging to a collection or a multi-volumed work to perform actions on them or disable them.
We thus have to make collection and hostId searchable in the UI.

**Comment by ponchofiesta** [comment]
HostId and Collections are now searchable in the UI. They are also shown below a work and are clickable to search more works.
