### ISSUE TITLE
Database automatic updates

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#132]
We have recently the database extended with a collections table and a work attribute, and of course, it is likely that we will have to do this also in the future with a running system.
For this case, it is necessary to have an automatic update possibility for the database. If we therby should work with flyway or something else I cannot say. A solution only using hibernate would of course be very nice, but is there one?

**Comment by ponchofiesta** [comment]
So far I think by only using Hibernate this is not possible. Hibernates SchemaUpdate can create and delete but not migrate the data. By going back to DBMS related SQL scripts it might be possible. We could write our own migration tool by simply running these migration scripts. But I don't think this is faster than using a framework.

Flyway seems to be good for small projects and easy to use. It only supports forward migrations which might be OK for production use. Biggest drawback is it needs migrationsscripts for every DBMS. Actually I was happy we are DBMS independent by using Hibernates SchemaExport.

Liquibase supports forward and backward migration. It saves the migration config in a generic file format and generates SQL by itself (like Hibernate does). But I assume it is more complex to implement.
