### ISSUE TITLE
Action creating PDF file containing all images

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#198]
We need an action creating a PDF from all original images of a work.
In a first version, it would be sufficient with a pdf from the images alone. For the future, we would however like to be able to create pdf with text underlies from images and ocr files.

**Comment by ponchofiesta** [comment]
I pushed a first try: f6640491e2e46f6dc227a79be804efd66e1cf693 (branch 198_pdf-creation)

Actually there is a new IFullConverter interface as the IConverter only converts from one master file. But there is much code both converters are using. Maybe we can wrap this in another interface and abstract class.

For now this is doing the conversion in a similar way as the single file process. There are similar actions, a converter and beans.

As the single file converter, this full pdf converter doesn't create A4 format pages. I think PDF creation should be done in the same way for both methods.

Please have a look.

**Comment by ponchofiesta** [comment]
This new commit expects an fptr entry for the PDF file in the METS/MODS file. This entry points to another entry in the filegroup DOWNLOAD which points to the PDF URL.
