### ISSUE TITLE
Login form not shown when /login is requested

### ISSUE THREAD

**Issue by ponchofiesta** [tuub/kitodo-mediaserver#66]
The login form is not shown if you open /login in the browser. If you open another restricted path (e.g. /works) you get redirected to /login and the form is shown.

**Comment by johlton** [comment]
Works for me.

**Comment by ponchofiesta** [comment]
@pbroman Could you check this bug again. We actually can not reproduce it. Maybe there was some change in the background that caused it and is now fixed... magic :)

**Comment by pbroman** [comment]
Works for me too now, case closed.
