### ISSUE TITLE
Reduce Mets/Mods by disabling work

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#77]
If a work is disabled, this is possibly due to a complaint of violation of personality rights. For this reason, there must be a possibility to reduce the mets/mods file by disabling a work. 
The reduction is used using a XSLT stylesheet (available in the internal wiki). The original file must be stored under a different name and restored at enabling the work. 
The performance of this reduction should at least be configurable, possibly selectable in the gui.

**Comment by ponchofiesta** [comment]
Now there is a new setting reduceMets in YML config which is the default value whether to reduce the METS file on disabling or not. The user can override this setting by disabling a work in UI.
The `WorkLockAction` now creates the backup METS file if requested and it will restore it on enabling if an original file exists.
