### ISSUE TITLE
Notifications / Events

### ISSUE THREAD

**Issue by pbroman** [tuub/kitodo-mediaserver#87]
We need a facility for notifications to admin by critical errors. This goes particularly for the importer but is relevant for the fileserver too, so the code should be in the core. 
Using this facility, one should be able to construct and send notification emails. The email could be an error message but also a report on the process of an import, containing infos and warnings. So one must be able to add content step by step and eventually send it with a subject.

**Comment by johlton** [comment]
To-Do: make sure that the notification buffer can be passed to other parts of the application which could get cumbersome pretty fast..

**Comment by pbroman** [comment]
I wouldn't do that. In a perfect world, yes, but I'm sure  we can live with a solution where the buffer cannot be passed around.
